name: deploy_docs

on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack Channel for notification 
        required: false
        default: openhexa-alerts
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides/**'
      - '.github/workflows/deploy_docs.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set configs
        id: config
        env:
          DEFAULT_GIT_REFERENCE: main
        run: |
          echo "GIT_REFERENCE=${{ github.ref_name || env.DEFAULT_GIT_REFERENCE }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.config.outputs.GIT_REFERENCE }}
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install mkdocs and dependencies
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - run: python -V && python -m venv ./venv && . ./venv/bin/activate && pip install -U pip && pip install -r docs/requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Environment info
        run: |
          . ./venv/bin/activate
          pip list

      - name: Deploy on Github pages
        run: |
          . ./venv/bin/activate
          mkdocs gh-deploy --config-file mkdocs.yml --force